services:
  - type: web
    name: livequeuemonitor
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      python -m pip install setuptools wheel
      pip install -r requirements.txt --no-cache-dir
      python manage.py collectstatic --noinput
    startCommand: gunicorn queuemanager.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: DATABASE_URL
        sync: false
      - key: PYTHONPATH
        value: /opt/render/project/src
    autoDeploy: true
